baseURL = './'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'default'
pluralizelisttitles = false
summarylength = 10

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 10

[[menus.main]]
name = 'Studium'
pageRef = '/studium'
weight = 11


[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[markup]
defaultMarkdownHandler = 'org'
  [markup.tableofcontents]
    endlevel = 2
    startlevel = 2

# removes the default 'categories' taxonomy
[taxonomies]
  tag = 'tags'

[params.author]
name = "Yan Cao"
