baseURL = './'
title = 'My New Hugo Site'
theme = 'default'
pluralizelisttitles = false
summarylength = 10

[markup]
defaultMarkdownHandler = 'org'
  [markup.tableofcontents]
    endlevel = 2
    startlevel = 2
  [markup.highlight]
    style = 'modus-operandi'

[languages]
  [languages.de]
    languageCode = 'de-DE'
    contentDir = 'content/de'
    languageName = 'Deutsch'
    weight = 3
    [languages.de.menus]
      [[languages.de.menus.main]]
        name = 'Home'
        pageRef = '/'
        weight = 10
      [[languages.de.menus.main]]
        name = 'Studium'
        pageRef = '/studium'
        weight = 20
  [languages.en]
    languageCode = 'en-US'
    contentDir = 'content/en'
    languageName = 'English'
    weight = 1
    [languages.en.menus]
      [[languages.en.menus.main]]
        name = 'Home'
        pageRef = '/'
        weight = 10
      [[languages.en.menus.main]]
        name = 'Posts'
        pageRef = '/posts'
        weight = 20
  [languages.zh]
    languageCode = 'zh-CN'
    contentDir = 'content/zh'
    languageName = '简体中文'
    weight = 2
    [languages.zh.menus]
      [[languages.zh.menus.main]]
        name = '主页'
        pageRef = '/'
        weight = 10
      [[languages.zh.menus.main]]
        name = '文章'
        pageRef = '/posts'
        weight = 20

# removes the default 'categories' taxonomy
[taxonomies]
  tag = 'tags'

[params.author]
name = "Yan Cao"
